version: '3.8'

services:
  main:
    image: rotate
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: rotator
    env_file:
      - .env
