version: '3.8'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"
        tag: rotator
    env_file:
      - .env
